_BASE_: yolov8_base.yaml

EXP_NAME: exp_yolov8_l_0

MODEL:
  SCALES: [1.00, 1.25, 1024]

DATALOADER:
  BATCH_SIZE: 40
  REFERENCE_BATCH_SIZE: 8
  REFERENCE_WORLD_SIZE: 1

SOLVER:
  MAX_ITER: 600000 # around 50 epochs for total_batch_size=4
  WARMUP_ITERS: 12000 # around 1 epoch
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 1e-5
  BASE_LR_END: 1e-6
  AMP:
    ENABLED: true

TRAINING:
  NUM_EPOCHS: 20
  EVAL_PERIOD: 1

WANDB:
  PROJECT: snn_detection
