MODEL:
  NAME: YOLOv8
  SCALES: [0.33, 0.25, 1024]
  NUM_CLASSES: 2

  BACKBONE:
    RGB:
      NAME: YOLOv8Backbone
      IN_CHANNELS: 3
      OUT_INDICES: [6, 4, -1]
      CONFIG:
        - name: Conv #0 [B,3,480,640] -> [B,64,240,320] /2
          repeat_nums: 1
          args:
            in_channels: 2
            out_channels: 64
            kernel_size: 3
            stride: 2
            padding: 1
        - name: Conv #1 [B,64,240,320] -> [B,128,120,160] /4
          repeat_nums: 1
          args:
            in_channels: 64
            out_channels: 128
            kernel_size: 3
            stride: 2
            padding: 1
        - name: C2f #2 [B,128,120,160] -> [B,128,120,160]
          repeat_nums: 3
          args:
            in_channels: 128
            out_channels: 128
            shortcut: true
        - name: Conv #3 [B,128,120,160] -> [B,256,60,80] /8
          repeat_nums: 1
          args:
            in_channels: 128
            out_channels: 256
            kernel_size: 3
            stride: 2
            padding: 1
        - name: C2f #4 [B,256,60,80] -> [B,256,60,80]
          repeat_nums: 6
          args:
            in_channels: 256
            out_channels: 256
            shortcut: true
        - name: Conv #5 [B,256,60,80] -> [B,512,30,40] /16
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 512
            kernel_size: 3
            stride: 2
            padding: 1
        - name: C2f #6 [B,512,30,40] -> [B,512,30,40]
          repeat_nums: 6
          args:
            in_channels: 512
            out_channels: 512
            shortcut: true
        - name: Conv #7 [B,512,30,40] -> [B,1024,15,20] /32
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 1024
            kernel_size: 3
            stride: 2
            padding: 1
        - name: C2f #8 [B,1024,15,20] -> [B,1024,15,20]
          repeat_nums: 3
          args:
            in_channels: 1024
            out_channels: 1024
            shortcut: true
        - name: SPPF #9 [B,1024,15,20] -> [B,1024,15,20]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 1024
            kernel_size: 5

  NECK:
    RGB:
      NAME: YOLOv8Neck
      IN_CHANNELS: 1024
      FROM_INDICES:
        [
          -1,
          -1,
          -1,
          [-1, 1],
          -1,
          -1,
          -1,
          [-1, 0],
          -1,
          -1,
          -1,
          [-1, 7],
          -1,
          -1,
          [-1, 3],
          -1,
        ]
      OUT_INDICES: [9, 12, 15]
      CONFIG:
        - name: Conv #0 [B,1024,15,20] -> [B,512,15,20]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 512
            kernel_size: 1
            stride: 1

        - name: UpSampling #1 [B,512,15,20] -> [B,512,30,40]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 512
            size: null
            scale_factor: [2, 2]
            mode: nearest

        - name: C2f #2 [B,512,30,40] -> [B,512,30,40]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 512
            shortcut: false

        - name: Concat #3 [B,512,30,40] -> [B,1024,30,40]
          repeat_nums: 1
          args:
            in_channels: 512
            from_channels: 512
            out_channels: 1024
            dimension: 1 # channel dim

        - name: Conv #4 [B,1024,30,40] -> [B,256,30,40]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 256
            kernel_size: 1
            stride: 1

        - name: UpSampling #5 [B,256,30,40] -> [B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 256
            size: null
            scale_factor: [2, 2]
            mode: nearest

        - name: C2f #6 [B,256,60,80] -> [B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 256
            shortcut: false

        - name: Concat #7 [B,256,60,80] -> [B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            from_channels: 256
            out_channels: 512
            dimension: 1 # channel dim

        - name: Conv #8 [B,512,60,80] -> [B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 256
            kernel_size: 1
            stride: 1

        - name: C2f #9 [B,256,60,80] -> [B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 256
            shortcut: false

        - name: Conv #10 [B,256,60,80] -> [B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 256
            kernel_size: 3
            stride: 2

        - name: Concat #11 [B,256,60,80] -> [B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            from_channels: 256
            out_channels: 512
            dimension: 1 # channel dim

        - name: C2f #12 [B,512,60,80] -> [B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 512
            shortcut: false

        - name: Conv #13 [B,512,60,80] -> [B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 512
            kernel_size: 3
            stride: 2

        - name: Concat #14 [B,512,60,80] -> [B,1024,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            from_channels: 512
            out_channels: 1024
            dimension: 1 # channel dim

        - name: C2f #15 [B,1024,60,80] -> [B,1024,60,80]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 1024
            shortcut: false

  HEAD:
    NAME: YOLOv8Head
    STRIDE: [8, 16, 32]
    WEIGHT: [7.5, 0.5, 1.5]

DATASETS:
  TRAIN: dsec_train
  VAL: dsec_val
  TEST: dsec_test
  MODALITY: image

