_BASE_: yolov8_base.yaml

EXP_NAME: exp_yolov8_l_0

MODEL:
  SCALES: [1.00, 1.00, 512]

DATALOADER:
  BATCH_SIZE: 24
  REFERENCE_BATCH_SIZE: 8
  REFERENCE_WORLD_SIZE: 1

DATASETS:
  TRANSFORMS:
    - name: Mosaic
      mosaic_size: [1280, 1280]
      close_mosaic_epoch: 10

    - name: ResizeKeepRatio
      short_edge_length: 640
      max_size: 640
      stride: 32
      sample_style: choice

    - name: RandomFlip


SOLVER:
  MAX_ITER: 600000 # around 50 epochs for total_batch_size=4
  WARMUP_ITERS: 12000 # around 1 epoch
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 1e-5
  BASE_LR_END: 1e-6
  AMP:
    ENABLED: true

TRAINING:
  NUM_EPOCHS: 20
  EVAL_PERIOD: 2

WANDB:
  PROJECT: snn_detection
