_BASE_: yolov8_base.yaml

EXP_NAME: exp_yolov8_n_0

MODEL:
  HEAD:
    NMS:
      DYNAMIC_CONF: true
      CONF_THRES: 0.25
      IOU_THRES: 0.45
      EXP_K: 0.5

DATALOADER:
  BATCH_SIZE: 32
  REFERENCE_BATCH_SIZE: 8
  REFERENCE_WORLD_SIZE: 1

DATASETS:
  MODALITY: events

  TRANSFORMS:
  - name: ResizeKeepRatio
    short_edge_length: 640
    max_size: 640
    stride: 32
    sample_style: choice

  - name: RandomFlip

SOLVER:
  MAX_ITER: 600000 # around 50 epochs for total_batch_size=4
  WARMUP_ITERS: 12000 # around 1 epoch
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 1e-4
  BASE_LR_END: 1e-5
  AMP:
    ENABLED: true

TRAINING:
  NUM_EPOCHS: 20
  EVAL_PERIOD: 1

WANDB:
  PROJECT: snn_detection
