MODEL:
  NAME: SpikeYOLO
  SPIKE_CONFIG:
    spike_mode: lif
    tau: 2.0
    v_threshold: 1.0
    v_reset: 0.0
    detach_reset: true
    backend: cupy
  SCALES: [0.33, 0.25, 1024]
  NUM_CLASSES: 2

  BACKBONE:
    EVENT:
      NAME: SpikeYOLOBackbone
      IN_CHANNELS: 3
      OUT_INDICES: [5, 3, -1]
      CONFIG:
        - name: DownSampling #0 [T,B,2,480,640] -> [T,B,128,120,160] /4
          repeat_nums: 1
          args:
            in_channels: 2
            out_channels: 128
            kernel_size: 7
            stride: 4
            padding: 2

        - name: ConvBlock1 #1 [T,B,128,120,160] -> [T,B,128,120,160]
          repeat_nums: 3
          args:
            in_channels: 128
            mlp_ratio: 4.0
            sep_kernel_size: 7
            group: false

        - name: DownSampling #2 [T,B,128,120,160] -> [T,B,256,60,80] /8
          repeat_nums: 1
          args:
            in_channels: 128
            out_channels: 256
            kernel_size: 3
            stride: 2
            padding: 1

        - name: ConvBlock1 #3 [T,B,256,60,80] -> [T,B,256,60,80]
          repeat_nums: 6
          args:
            in_channels: 256
            mlp_ratio: 4.0
            sep_kernel_size: 7
            group: false

        - name: DownSampling #4 [T,B,256,60,80] -> [T,B,512,30,40] /16
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 512
            kernel_size: 3
            stride: 2
            padding: 1

        - name: ConvBlock2 #5 [T,B,512,30,40] -> [T,B,512,30,40]
          repeat_nums: 9
          args:
            in_channels: 512
            mlp_ratio: 3.0
            sep_kernel_size: 7
            group: false

        - name: DownSampling #6 [T,B,512,30,40] -> [T,B,1024,15,20] /32
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 1024
            kernel_size: 3
            stride: 2
            padding: 1

        - name: ConvBlock2 #7 [T,B,1024,15,20] -> [T,B,1024,15,20]
          repeat_nums: 1
          args:
            in_channels: 512
            mlp_ratio: 2.0
            sep_kernel_size: 7
            group: false

        - name: SpikeSPPF #8 [T,B,1024,15,20] -> [T,B,1024,15,20]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 1024
            kernel_size: 5

  NECK:
    EVENT:
      NAME: SpikeYOLONeck
      IN_CHANNELS: 1024
      FROM_INDICES:
        [
          -1,
          -1,
          -1,
          [-1, 1],
          -1,
          -1,
          -1,
          [-1, 0],
          -1,
          -1,
          -1,
          [-1, 7],
          -1,
          -1,
          [-1, 3],
          -1,
        ]
      OUT_INDICES: [9, 12, 15]
      CONFIG:
        - name: SpikeConv #0 [T,B,1024,15,20] -> [T,B,512,15,20]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 512
            kernel_size: 1
            stride: 1

        - name: UpSampling #1 [T,B,512,15,20] -> [T,B,512,30,40]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 512
            size: null
            scale_factor: [1, 2, 2]
            mode: nearest

        - name: ConvBlock2 #2 [T,B,512,30,40] -> [T,B,512,30,40]
          repeat_nums: 1
          args:
            in_channels: 512
            mlp_ratio: 3.0
            sep_kernel_size: 7
            group: false

        - name: Concat #3 [T,B,512,30,40] -> [T,B,1024,30,40]
          repeat_nums: 1
          args:
            in_channels: 512
            from_channels: 512
            out_channels: 1024
            dimension: 2 # channel dim

        - name: SpikeConv #4 [T,B,1024,30,40] -> [T,B,256,30,40]
          repeat_nums: 1
          args:
            in_channels: 1024
            out_channels: 256
            kernel_size: 1
            stride: 1

        - name: UpSampling #5 [T,B,256,30,40] -> [T,B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 256
            size: null
            scale_factor: [1, 2, 2]
            mode: nearest

        - name: ConvBlock1 #6 [T,B,256,60,80] -> [T,B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            mlp_ratio: 4.0
            sep_kernel_size: 7
            group: false

        - name: Concat #7 [T,B,256,60,80] -> [T,B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            from_channels: 256
            out_channels: 512
            dimension: 2 # channel dim

        - name: SpikeConv #8 [T,B,512,60,80] -> [T,B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 256
            kernel_size: 1
            stride: 1

        - name: ConvBlock1 #9 [T,B,256,60,80] -> [T,B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            mlp_ratio: 4.0
            kernel_size: 7
            group: false

        - name: SpikeConv #10 [T,B,256,60,80] -> [T,B,256,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            out_channels: 256
            kernel_size: 3
            stride: 2

        - name: Concat #11 [T,B,256,60,80] -> [T,B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 256
            from_channels: 256
            out_channels: 512
            dimension: 2 # channel dim

        - name: ConvBlock2 #12 [T,B,512,60,80] -> [T,B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            mlp_ratio: 3.0
            kernel_size: 7
            group: false

        - name: SpikeConv #13 [T,B,512,60,80] -> [T,B,512,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            out_channels: 512
            kernel_size: 3
            stride: 2

        - name: Concat #14 [T,B,512,60,80] -> [T,B,1024,60,80]
          repeat_nums: 1
          args:
            in_channels: 512
            from_channels: 512
            out_channels: 1024
            dimension: 2 # channel dim

        - name: ConvBlock2 #15 [T,B,1024,60,80] -> [T,B,1024,60,80]
          repeat_nums: 1
          args:
            in_channels: 1024
            mlp_ratio: 1.0
            kernel_size: 7
            group: false

  HEAD:
    NAME: SpikeYOLOHead
    STRIDE: [8, 16, 32]
    WEIGHT: [7.5, 0.5, 1.5]

DATASETS:
  TYPE: dsec
  TRAIN: dsec_train
  VAL: dsec_val
  TEST: dsec_test
  MODALITY: events
