_BASE_: spike_yolo_base.yaml

EXP_NAME: exp_n_0

MODEL:
  SPIKE_CONFIG:
    spike_mode: lif
    tau: 2.0
    v_threshold: 1.0
    v_reset: 0.0
    detach_reset: true
    backend: cupy

  HEAD:
    NMS:
      DYNAMIC_CONF: false
      CONF_THRES: 1e-3
      EXP_K: 1.0

DATALOADER:
  BATCH_SIZE: 10
  REFERENCE_BATCH_SIZE: 8
  REFERENCE_WORLD_SIZE: 1

DATASETS:
  TRANSFORMS:
    - name: Mosaic
      mosaic_size: [1280, 1280]
      close_mosaic_epoch: 20

    - name: ResizeKeepRatio
      short_edge_length: 640
      max_size: 640
      stride: 32
      sample_style: choice

    - name: RandomFlip

SOLVER:
  MAX_ITER: 600000 # around 100 epochs for total_batch_size=4
  WARMUP_ITERS: 60000 # around 10 epoch
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 1e-3
  BASE_LR_END: 5e-4
  AMP:
    ENABLED: true

TRAINING:
  NUM_EPOCHS: 100
  EVAL_PERIOD: 2
  SYNC_BN: true

WANDB:
  PROJECT: snn_detection
